/**
 * scripts/compile.mjs
 * ---------------------------------------------------------------------------
 * Dependency-light Solidity compiler for this repo. Compiles
 * `contracts/SavingsJar.sol` with solc-js and writes:
 *
 *   - config/abi/savingsJar.abi.ts   -> TypeScript ABI (`as const`, viem-ready)
 *   - artifacts/SavingsJar.json      -> full solc artifact (abi + bytecode)
 *
 * Usage:
 *   npm run compile
 *
 * solc is an optional dev dependency. If it is not installed locally the script
 * falls back to a scratch install under ~/.solcbuild.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SOL_PATH = resolve(ROOT, 'contracts/SavingsJar.sol');
const CONTRACT_NAME = 'SavingsJar';

const require = createRequire(import.meta.url);

function loadSolc() {
  const candidates = ['solc', resolve(process.env.HOME || '/root', '.solcbuild/node_modules/solc')];
  for (const candidate of candidates) {
    try {
      return require(candidate);
    } catch {
      /* try next */
    }
  }
  throw new Error('solc not found. Run: npm i -D solc@0.8.28');
}

const solc = loadSolc();
console.log(`[compile] solc ${solc.version()}`);

const source = readFileSync(SOL_PATH, 'utf8');

const input = {
  language: 'Solidity',
  sources: { 'SavingsJar.sol': { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'paris',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

let failed = false;
for (const err of output.errors ?? []) {
  if (err.severity === 'error') failed = true;
  console.log(err.formattedMessage.trim());
}
if (failed) {
  console.error('[compile] FAILED');
  process.exit(1);
}

const compiled = output.contracts['SavingsJar.sol'][CONTRACT_NAME];
const abi = compiled.abi;
const bytecode = compiled.evm.bytecode.object;

console.log(`[compile] OK - ${abi.length} ABI entries, ${(bytecode.length / 2 - 1) | 0} bytes of init code`);

// ---------------------------------------------------------------------------
// Write artifacts
// ---------------------------------------------------------------------------
mkdirSync(resolve(ROOT, 'artifacts'), { recursive: true });
mkdirSync(resolve(ROOT, 'config/abi'), { recursive: true });

writeFileSync(
  resolve(ROOT, 'artifacts/SavingsJar.json'),
  `${JSON.stringify({ contractName: CONTRACT_NAME, abi, bytecode: `0x${bytecode}` }, null, 2)}\n`,
);

const tsAbi = `/**
 * AUTO-GENERATED by \`npm run compile\` - do not edit by hand.
 * Source: contracts/SavingsJar.sol (solc ${solc.version()})
 */
export const savingsJarAbi = ${JSON.stringify(abi, null, 2)} as const;

export type SavingsJarAbi = typeof savingsJarAbi;
`;

writeFileSync(resolve(ROOT, 'config/abi/savingsJar.abi.ts'), tsAbi);

console.log('[compile] wrote config/abi/savingsJar.abi.ts');
console.log('[compile] wrote artifacts/SavingsJar.json');

if (!existsSync(resolve(ROOT, 'config/abi/savingsJar.abi.ts'))) process.exit(1);
