/**
 * Barrel for the ABIs used by the front-end.
 * `savingsJar.abi.ts` is auto-generated by `npm run compile`.
 */
export { savingsJarAbi, type SavingsJarAbi } from "./savingsJar.abi";
export { erc20Abi } from "./erc20.abi";
